Core: Avoid including <sstream> with EIGEN_NO_IO
This allows using the Eigen/Dense header in embedded environments using
libc++ built with -DLIBCXX_ENABLE_LOCALIZATION=OFF. Without this change,
including Eigen/Dense will result in the following compiler error:
error: "<locale.h> is not supported since libc++ has been configured without support for localization

I did not include a test for this change since we would have to mock
headers for an entire C++ standard library without iostream support.